[[plugins]]
repo = 'chriskempson/base16-vim'
hook_add = '''
  " autocmd EN VimEnter * nested colorscheme base16-classic-dark
'''

[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
  " autocmd EN VimEnter * nested colorscheme tender
'''

[[plugins]]
repo = 'kristijanhusak/vim-hybrid-material'
hook_add = '''
  " autocmd EN VimEnter * nested colorscheme hybrid_reverse
'''


[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  autocmd EN VimEnter * nested colorscheme iceberg
'''

[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = '''
  " autocmd EN VimEnter * nested colorscheme nord
'''

[[plugins]]
repo = 'ErichDonGubler/vim-sublime-monokai'

[[plugins]]
repo = 'ayu-theme/ayu-vim'
hook_add = '''
  " let ayucolor="light"
  let ayucolor="mirage"
  " let ayucolor="dark"
  " autocmd EN VimEnter * nested colorscheme ayu
'''
