[[plugins]]
repo = 'chriskempson/base16-vim'
hook_add = '''
  " autocmd EN VimEnter * nested colorscheme base16-classic-dark
'''

[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
  " autocmd EN VimEnter * nested colorscheme tender
'''

[[plugins]]
repo = 'kristijanhusak/vim-hybrid-material'
hook_add = '''
  " autocmd EN VimEnter * nested colorscheme hybrid_reverse
'''


[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  autocmd EN VimEnter * nested colorscheme iceberg
'''

[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = '''
  " autocmd EN VimEnter * nested colorscheme nord
'''

[[plugins]]
repo = 'ayu-theme/ayu-vim'
hook_add = '''
  " let ayucolor="light"
  let ayucolor="mirage"
  " let ayucolor="dark"
  " autocmd EN VimEnter * nested colorscheme ayu
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
if = ''' exists('g:rich') '''
hook_add = '''
  source ~/.vim/dein/sub/lightline.vim
  let g:lightline.colorscheme = 'iceberg'
  " let g:lightline.colorscheme = 'nord'
  " let g:lightline.colorscheme = 'hybrid'
'''

[[plugins]]
repo = 'endaaman/lightline-hybrid.vim'
if = ''' exists('g:rich') '''
depends = ['lightline.vim']
hook_add = '''
 " let g:hybrid_reduced_contrast = 1
'''
