[[plugins]]
repo = 'chriskempson/base16-vim'
hook_add = '''
  " autocmd E VimEnter * nested colorscheme base16-default-dark
'''

[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
  " autocmd E VimEnter * nested colorscheme tender
'''

[[plugins]]
repo = 'kristijanhusak/vim-hybrid-material'
hook_add = '''
  " autocmd E VimEnter * nested colorscheme hybrid_reverse
'''


[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  autocmd E VimEnter * nested colorscheme iceberg
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  source ~/.vim/dein/sub/lightline.vim
  let g:lightline.colorscheme = 'iceberg'
  " let g:lightline.colorscheme = 'hybrid'
'''

[[plugins]]
repo = 'endaaman/lightline-hybrid.vim'
depends = ['lightline.vim']
hook_add = '''
'''
