[[plugins]]
repo = 'chriskempson/base16-vim'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'kristijanhusak/vim-hybrid-material'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_source = '''
  colorscheme iceberg
'''

[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'ErichDonGubler/vim-sublime-monokai'

[[plugins]]
repo = 'ayu-theme/ayu-vim'
hook_add = '''
  " let ayucolor="light"
  let ayucolor="mirage"
  " let ayucolor="dark"
  " autocmd EN VimEnter * nested colorscheme ayu
'''
