[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
  nnoremap <Space>a :<C-u>Defx<CR>
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  if !exists('g:deoplete#omni#input_patterns')
    let g:deoplete#omni#input_patterns = {}
  endif
  let g:deoplete#omni#functions = {}
  " let g:deoplete#omni#input_patterns.python = '\h\w*\|[^. \t]\.\w*'
  " let g:deoplete#omni#functions.python = 'jedi#completions'
  inoremap <expr> <TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
  inoremap <expr> <S-TAB> pumvisible() ? "\<C-p>" : "\<TAB>"
'''
hook_source = '''
  call deoplete#custom#option({
    \ 'auto_complete_delay': 100,
    \ 'camel_case': 1,
    \ 'ignore_case': 0,
    \ 'smart_case': 1,
    \ })
'''

[[plugins]]
repo = 'deoplete-plugins/deoplete-jedi'
on_ft = ['python']
hook_add = '''
  let g:deoplete#sources#jedi#show_docstring = 0
'''

[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
depends = ['deoplete.nvim']
on_ft = ['rust']
hook_add = '''
  " TODO: use
  "   system('which racer')
  " and
  "
  let g:deoplete#sources#rust#racer_binary = Chomp(system('which racer'))
  let g:deoplete#sources#rust#rust_source_path = Chomp(system('rustc --print sysroot')) . '/lib/rustlib/src/rust/src'
  let g:deoplete#sources#rust#show_duplicates = 1
  let g:deoplete#sources#rust#disable_keymap = 1
  " nnoremap <buffer> <Space>gd <plug>DeopleteRustGoToDefinitionDefault
  nnoremap <buffer> <Space>K <plug>DeopleteRustShowDocumentation
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
ev = '738670414117c1065791c3c3b6a299a3a7cab5ba'
hook_add = '''
  call denite#custom#map('_', '<Esc>', '<denite:leave_mode>', 'noremap')
  call denite#custom#map('_', '<Tab>', '<denite:move_to_next_line>', 'noremap')
  call denite#custom#map('_', '<S-Tab>', '<denite:move_to_previous_line>', 'noremap')
  call denite#custom#map('_', '<C-d>', '<denite:quit>', 'noremap')
  call denite#custom#map('insert', '<C-j>', '<denite:choose_action>', 'noremap')
  call denite#custom#map('insert', '<C-k>', '<denite:do_action:echo>', 'noremap')
  call denite#custom#map('insert', '<C-t>', '<denite:do_action:tabopen>', 'noremap')
  call denite#custom#map('insert', '<C-p>', '<denite:do_action:split>', 'noremap')
  call denite#custom#map('insert', '<C-s>', '<denite:do_action:vsplit>', 'noremap')
  call denite#custom#map('insert', '<C-y>', '<denite:do_action:yank>', 'noremap')
  call denite#custom#map('insert', '<C-o>', '<denite:do_action:xdg-open>', 'noremap')
  call denite#custom#map('insert', '<C-a>', '<Home>')
  call denite#custom#map('insert', '<C-e>', '<End>')
  call denite#custom#map('insert', '<C-f>', '<Right>')
  call denite#custom#map('insert', '<C-b>', '<Left>')
  call denite#custom#map('insert', '<PageDown>', '<denite:scroll_page_forwards>')
  call denite#custom#map('insert', '<PageUp>', '<denite:scroll_page_backwards>')

  call denite#custom#action('file', 'xdg-open', 'DeniteFileActionXdgOpen')
  call denite#custom#action('word', 'prepend', 'DeniteWordActionPrepend')
  call denite#custom#action('word', 'yank', 'DeniteWordActionYank')
  call denite#custom#action('command', 'tabopen', 'DeniteCommandActionTabopen')
  call denite#custom#action('_', 'nop', 'DeniteCommonActionNop', {'is_quit': 0})

  call denite#custom#filter('matcher_ignore_globs', 'ignore_globs', [
    \ '*~', '*.o', '*.exe', '*.bak',
    \ '.DS_Store', '*.pyc', '*.sw[po]', '*.class',
    \ '.hg/', '.git/', '.bzr/', '.svn/',
    \ 'tags', 'tags-*',
    \ 'node_modules/', '*.ttf', 'vendor/'
    \ ])

  call denite#custom#source('_', 'matchers', ['matcher_substring'])
  call denite#custom#option('_', { 'highlight_matched_char': 'Title' })
  if get(g:, 'rich')
    call denite#custom#option('_', 'prompt', '')
  endif
	call denite#custom#source('grep', 'converters', ['converter/abbr_word'])

  nnoremap <Space>o :<C-u>Denite outline<CR>
  nnoremap <Space>O :<C-u>Denite file/old<CR>
  nnoremap <Space>J :<C-u>Denite jump<CR>
  nnoremap <Space>b :<C-u>Denite buffer<CR>
  nnoremap <Space>m :<C-u>Denite mark<CR>
  nnoremap <Space>M :<C-u>Denite menu<CR>
  nnoremap <Space>g :<C-u>Denite grep -no-empty<CR>
  nnoremap <Space>G :<C-u>Denite grep -input=`@0`<CR>
  nnoremap <Space>? :<C-u>Denite grep -input=`@/`<CR>
  nnoremap <Space>W :<C-u>Denite grep -no-empty -input=`expand("<cword>")`<CR>
  nnoremap <Space>c :<C-u>Denite command<CR>
  nnoremap <Space>C :<C-u>Denite command_history<CR>
  nnoremap <Space>h :<C-u>Denite help -default-action=tabopen<CR>
  nnoremap <Space>p :<C-u>Denite my/register<CR>
  nnoremap <Space>P :<C-u>Denite my/register -default-action=prepend<CR>
  nnoremap <Space>r :<C-u>Denite my/register -default-action=yank<CR>
  nnoremap <Space>d :<C-u>Denite my/git/status<CR>
  nnoremap <Space>f :<C-u>Denite `finddir('.git', ';') != '' ? 'my/git/all' : 'file/rec'`<CR>
  nnoremap <Space>F :<C-u>Denite `finddir('.git', ';') != '' ? 'my/git/all' : 'file/rec'` -input=`expand("<cword>")`<CR>
  nnoremap <Space>y :<C-u>Denite menu:yank<CR>
  nnoremap <Space>, :<C-u>Denite file/rec -path=,<CR>
  nnoremap <Space>a :<C-u>DeniteBufferDir file/rec<CR>
  nnoremap <Space>A :<C-u>Denite directory_rec<CR>
  nnoremap <Space>l :<C-u>Denite my/git/log<CR>
  nnoremap <Space><C-n> :<C-u>Denite -resume -cursor-pos=+1 -immediately<CR>
  nnoremap <Space><C-p> :<C-u>Denite -resume -cursor-pos=-1 -immediately<CR>
  nnoremap <Space><Space> :<C-u>Denite -resume<CR>

  let s:menus = {}
  let s:menus.yank = { 'description': 'Yank file name or path' }
  let s:menus.yank.command_candidates = [
    \ ['File name', 'call YankFileName()'],
    \ ['Relative path', 'call YankRelativePath()'],
    \ ['Full path', 'call YankFullPath()'],
    \ ]
  let s:menus.CaseMaster = { 'description': 'Convert word case style' }
  let s:menus.CaseMaster.command_candidates = [
    \ ['To snake_case', 'CaseMasterConvertToSnake'],
    \ ['To kebab-case', 'CaseMasterConvertToKebab'],
    \ ['To camelCase', 'CaseMasterConvertToCamel'],
    \ ['To PascalCase', 'CaseMasterConvertToPascal'],
    \ ]
  let s:menus.Highlight = { 'description': 'Check highlight' }
  let s:menus.Highlight.command_candidates = [
    \ ['Highlight test', 'so $VIMRUNTIME/syntax/hitest.vim | execute "normal \<C-w>\T"'],
    \ ['Color test', 'so $VIMRUNTIME/syntax/colortest.vim | execute "normal \<C-w>\T"'],
    \ ]
  call denite#custom#var('menu', 'menus', s:menus)

  call denite#custom#alias('source', 'my/git/all', 'file/rec')
  call denite#custom#var('my/git/all', 'command',
    \ ['git', 'ls-files', '--cached', '--others', '--exclude-standard'])

  if executable('ag')
    call denite#custom#var('file/rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
    call denite#custom#var('grep', 'command', ['ag'])
    call denite#custom#var('grep', 'default_opts', ['--vimgrep'])
    call denite#custom#var('grep', 'recursive_opts', [])
    call denite#custom#var('grep', 'pattern_opt', [])
    call denite#custom#var('grep', 'separator', ['--'])
    call denite#custom#var('grep', 'final_opts', [])
  endif
'''
