[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  " let g:deoplete#enable_at_startup = 1
  let g:deoplete#enable_at_startup = 1
  if !exists('g:deoplete#omni#input_patterns')
    let g:deoplete#omni#input_patterns = {}
  endif

  inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
  inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<TAB>"
'''


[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
'''
