[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#enable_ignore_case = 0
  if !exists('g:deoplete#omni#input_patterns')
    let g:deoplete#omni#input_patterns = {}
  endif

  inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
  inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<TAB>"

  let g:deoplete#omni#functions = {}
  let g:deoplete#omni#input_patterns = {}
  " let g:deoplete#omni#input_patterns.python = '\h\w*\|[^. \t]\.\w*'
  " let g:deoplete#omni#functions.python = 'jedi#completions'
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
rev = '0f124c636495dd230fad38f678a80211149b0c78'
hook_add = '''
  call denite#custom#map(
  \ '_',
  \ '<Tab>',
  \ '<denite:move_to_next_line>',
  \ 'noremap'
  \)
  call denite#custom#map(
  \ '_',
  \ '<S-Tab>',
  \ '<denite:move_to_previous_line>',
  \ 'noremap'
  \)
  call denite#custom#map(
  \ '_',
  \ '<C-d>',
  \ '<denite:quit>',
  \ 'noremap'
  \)
  call denite#custom#map(
  \ '_',
  \ '<C-f>',
  \ '<denite:choose_action>',
  \ 'noremap'
  \)
  call denite#custom#map(
  \ 'insert',
  \ '<C-t>',
  \ '<denite:do_action:tabopen>',
  \ 'noremap'
  \)
  call denite#custom#map(
  \ 'insert',
  \ '<C-p>',
  \ '<denite:do_action:split>',
  \ 'noremap'
  \)
  call denite#custom#map(
  \ 'insert',
  \ '<C-s>',
  \ '<denite:do_action:vsplit>',
  \ 'noremap'
  \)
  call denite#custom#map(
  \ 'insert',
  \ '<C-y>',
  \ '<denite:do_action:yank>',
  \ 'noremap'
  \)

  call denite#custom#filter('matcher_ignore_globs', 'ignore_globs', [
  \ '*~', '*.o', '*.exe', '*.bak',
  \ '.DS_Store', '*.pyc', '*.sw[po]', '*.class',
  \ '.hg/', '.git/', '.bzr/', '.svn/',
  \ 'tags', 'tags-*',
  \ 'node_modules/', '*.ttf', 'vendor/'
  \ ])

  call denite#custom#source('_', 'matchers', ['matcher_substring'])
  call denite#custom#source('grep', 'matchers', ['matcher_cpsm'])

  nnoremap <Space>b :<C-u>Denite buffer<CR>
  nnoremap <Space>m :<C-u>Denite file_mru<CR>
  nnoremap <Space>o :<C-u>Denite file_old<CR>
  nnoremap <Space>g :<C-u>Denite grep<CR>
  nnoremap <Space>p :<C-u>Denite register<CR>
  nnoremap <Space>c :<C-u>Denite colorscheme<CR>
  nnoremap <Space>l :<C-u>Denite unite:outline<CR>
  nnoremap <Space>z :<C-u>Denite -resume<CR>
  nnoremap <Space>h :<C-u>Denite help<CR>
  nnoremap <Space>a :<C-u>Denite file_rec<CR>
  nnoremap <Space>d :<C-u>Denite file_rec/untracked file_rec/diff<CR>
  nnoremap <Space>f :<C-u>Denite file_rec/untracked file_rec/git<CR>
  nnoremap <Space>, :<C-u>Denite file_rec -path=,<CR>

  if executable('ag')
    call denite#custom#var('file_rec', 'command',
    \ ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])

    call denite#custom#var('grep', 'command', ['ag'])
    call denite#custom#var('grep', 'default_opts', ['-i', '--vimgrep'])
    call denite#custom#var('grep', 'recursive_opts', [])
    call denite#custom#var('grep', 'pattern_opt', [])
    call denite#custom#var('grep', 'separator', ['--'])
    call denite#custom#var('grep', 'final_opts', [])
  endif

  call denite#custom#alias('source', 'file_rec/git', 'file_rec')
  call denite#custom#var('file_rec/git', 'command',
  \ ['git', 'ls-files', '-co', '--exclude-standard'])

  call denite#custom#alias('source', 'file_rec/diff', 'file_rec')
  call denite#custom#var('file_rec/diff', 'command',
  \ ['git', 'diff-files', '--name-only'])

  call denite#custom#alias('source', 'file_rec/untracked', 'file_rec')
  call denite#custom#var('file_rec/untracked', 'command',
  \ ['git', 'ls-files', '--others', '--exclude-standard'])

  " call denite#custom#source('file_mru', 'converters', ['converter_relative_word'])
'''
depends = ['vimproc', 'unite.vim', 'unite-outline']

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'Shougo/unite-outline'
depends = ['vimproc', 'unite.vim']

[[plugins]]
repo = 'Shougo/unite.vim'
depends = ['vimproc']
