[[plugins]]
repo = 'scrooloose/nerdtree'
# if = ''' 1 '''
hook_add = '''
  " autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
  autocmd FileType nerdtree setlocal nolist
  function! NERDTreeCustom()
    if strlen(expand('%')) > 0
      NERDTreeFind
    else
      NERDTree
    endif
  endfunction
  command! -nargs=* -bar -bang -count=0 -complete=dir NERDTreeCustom <args>
  nnoremap <C-g> :<C-u>call NERDTreeCustom()<CR>

  let g:NERDTreeShowHidden = 1
  let g:NERDTreeHijackNetrw = 1
  let g:NERDTreeMinimalUI = 1
  let g:NERDTreeQuitOnOpen = 1
  let g:NERDTreeWinSize = 60

  autocmd FileType nerdtree setlocal nolist  "if you show hidden characters, this hides them in NERDTree

  let g:NERDTreeDirArrows = 1
  if !exists('g:rich')
    let g:NERDTreeDirArrowExpandable = '|'
    let g:NERDTreeDirArrowCollapsible = '-'
  endif
'''

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
# if = ''' exists('g:rich') '''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
# if = ''' exists('g:rich') '''
hook_add = '''
  let g:NERDTreeIndicatorMapCustom = {
    " \ 'Staged'    : '',
    \ 'Staged'    : '',
    \ 'Modified'  : '',
    \ 'Untracked' : '',
    \ 'Renamed'   : '➜',
    \ 'Unmerged'  : '═',
    \ 'Deleted'   : '✖',
    \ 'Clean'     : '✔︎',
    \ 'Dirty'     : '',
    \ 'Ignored'   : '',
    \ 'Unknown'   : '  '
    \ }
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'
# if = ''' exists('g:rich') '''
hook_add = '''
  let g:DevIconsEnableFoldersOpenClose = 1
  let g:WebDevIconsNerdTreeAfterGlyphPadding = ' '
  let g:WebDevIconsUnicodeDecorateFileNodes = 1
  let g:WebDevIconsUnicodeDecorateFileNodesDefaultSymbol = ''
  let g:WebDevIconsUnicodeDecorateFolderNodes = 1
  let g:WebDevIconsUnicodeGlyphDoubleWidth = 1

  let g:NERDTreeDirArrowCollapsible = nr2char(8200)
  let g:NERDTreeDirArrowExpandable = nr2char(8200)

  autocmd EN VimEnter * let g:webdevicons_conceal_nerdtree_brackets = 1
  let g:webdevicons_conceal_nerdtree_brackets = 1

  " let g:DevIconsDefaultFolderOpenSymbol = '▾'
  " let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = '▸'
  " let g:DevIconsDefaultFolderOpenSymbol = ''
  " let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = ''
  " let g:DevIconsDefaultFolderOpenSymbol = ''
  " let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = ''
  " let g:DevIconsDefaultFolderOpenSymbol = ''
  " let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = ''
  let g:DevIconsDefaultFolderOpenSymbol = ''
  let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = ''
'''

[[plugins]]
repo = 'aufgang001/vim-nerdtree_plugin_open'
hook_add = '''
  let g:nerdtree_plugin_open_cmd = 'xdg-open'
'''
