[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  " autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
  autocmd FileType nerdtree setlocal nolist
  function! NERDTreeCustom()
    if strlen(expand('%')) > 0
      NERDTreeFind
    else
      NERDTree
    endif
  endfunction
  command! -nargs=* -bar -bang -count=0 -complete=dir NERDTreeCustom <args>
  nnoremap <C-g> :<C-u>call NERDTreeCustom()<CR>

  let g:NERDTreeShowHidden = 1
  let g:NERDTreeHijackNetrw = 1
  let g:NERDTreeMinimalUI = 1
  let g:NERDTreeQuitOnOpen = 1

  autocmd FileType nerdtree setlocal nolist  "if you show hidden characters, this hides them in NERDTree
'''

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
hook_add = '''
  if exists('g:has_custom_font')
    let g:NERDTreeIndicatorMapCustom = {
      " \ 'Staged'    : '',
      \ 'Staged'    : '',
      \ 'Modified'  : '',
      \ 'Untracked' : '',
      \ 'Renamed'   : '➜',
      \ 'Unmerged'  : '═',
      \ 'Deleted'   : '✖',
      \ 'Clean'     : '✔︎',
      \ 'Dirty'     : '',
      \ 'Ignored'   : '',
      \ 'Unknown'   : '  '
      \ }
  endif
'''

[[plugins]]
repo = 'aufgang001/vim-nerdtree_plugin_open'
hook_add = '''
  let g:nerdtree_plugin_open_cmd = 'xdg-open'
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
  if exists('g:has_custom_font')
    let g:DevIconsEnableFoldersOpenClose = 1
    let g:WebDevIconsNerdTreeAfterGlyphPadding = ' '
    let g:WebDevIconsUnicodeDecorateFileNodes = 1
    let g:WebDevIconsUnicodeDecorateFileNodesDefaultSymbol = ''
    let g:WebDevIconsUnicodeDecorateFolderNodes = 1
    let g:WebDevIconsUnicodeGlyphDoubleWidth = 1

    let g:NERDTreeDirArrowCollapsible = nr2char(8200)
    let g:NERDTreeDirArrowExpandable = nr2char(8200)

    autocmd E VimEnter * let g:webdevicons_conceal_nerdtree_brackets = 1
    let g:webdevicons_conceal_nerdtree_brackets = 1

    " let g:DevIconsDefaultFolderOpenSymbol = '▾'
    " let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = '▸'
    " let g:DevIconsDefaultFolderOpenSymbol = ''
    " let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = ''
    " let g:DevIconsDefaultFolderOpenSymbol = ''
    " let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = ''
    " let g:DevIconsDefaultFolderOpenSymbol = ''
    " let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = ''
    let g:DevIconsDefaultFolderOpenSymbol = ''
    let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = ''
  endif
'''
