[[plugins]]
repo = 'scrooloose/nerdtree'
depends = ['vim-devicons', 'nerdtree-git-plugin']
hook_add = '''
  " autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
  autocmd FileType nerdtree setlocal nolist
  function! NERDTreeCustom()
    if strlen(expand('%')) > 0
      NERDTreeFind
    else
      NERDTree
    endif
  endfunction
  command! -nargs=* -bar -bang -count=0 -complete=dir NERDTreeCustom <args>
  nnoremap <C-g> :<C-u>call NERDTreeCustom()<CR>

  let g:NERDTreeShowHidden = 1
  let g:NERDTreeHijackNetrw = 1
  let g:NERDTreeMinimalUI = 1
  let g:NERDTreeQuitOnOpen = 1

  autocmd FileType nerdtree setlocal nolist  "if you show hidden characters, this hides them in NERDTree
'''

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
depends = ['nerdtree']

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
if = "exists('g:has_custom_font')"
hook_add = '''
  let g:NERDTreeIndicatorMapCustom = {
  " \ 'Staged'    : '',
  \ 'Staged'    : '',
  \ 'Modified'  : '',
  \ 'Untracked' : '',
  \ 'Renamed'   : '➜',
  \ 'Unmerged'  : '═',
  \ 'Deleted'   : '✖',
  \ 'Clean'     : '✔︎',
  \ 'Dirty'     : '',
  \ 'Ignored'   : '',
  \ 'Unknown'   : '  '
  \ }
'''

[[plugins]]
repo = 'aufgang001/vim-nerdtree_plugin_open'
hook_add = '''
  let g:nerdtree_plugin_open_cmd = 'xdg-open'
'''
