[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  source ~/.vim/dein/sub/lightline.vim
  let g:lightline.colorscheme = 'iceberg'
  " let g:lightline.colorscheme = 'nord'
  " let g:lightline.colorscheme = 'hybrid'
'''

[[plugins]]
repo = 'endaaman/lightline-hybrid.vim'
depends = ['lightline.vim']
hook_add = '''
 " let g:hybrid_reduced_contrast = 1
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
hook_add = '''
  let g:NERDTreeIndicatorMapCustom = {
    " \ 'Staged'    : '',
    \ 'Staged'    : '',
    \ 'Modified'  : '',
    \ 'Untracked' : '',
    \ 'Renamed'   : '➜',
    \ 'Unmerged'  : '═',
    \ 'Deleted'   : '✖',
    \ 'Clean'     : '✔︎',
    \ 'Dirty'     : '',
    \ 'Ignored'   : '',
    \ 'Unknown'   : '  '
    \ }
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
  let g:DevIconsEnableFoldersOpenClose = 1
  let g:WebDevIconsNerdTreeAfterGlyphPadding = ' '
  let g:WebDevIconsUnicodeDecorateFileNodes = 1
  let g:WebDevIconsUnicodeDecorateFileNodesDefaultSymbol = ''
  let g:WebDevIconsUnicodeDecorateFolderNodes = 1
  let g:WebDevIconsUnicodeGlyphDoubleWidth = 1

  let g:webdevicons_conceal_nerdtree_brackets = 1

  " let g:DevIconsDefaultFolderOpenSymbol = '▾'
  " let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = '▸'
  " let g:DevIconsDefaultFolderOpenSymbol = ''
  " let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = ''
  " let g:DevIconsDefaultFolderOpenSymbol = ''
  " let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = ''
  " let g:DevIconsDefaultFolderOpenSymbol = ''
  " let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = ''
  let g:DevIconsDefaultFolderOpenSymbol = ''
  let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = ''
'''
