[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'gabrielelana/vim-markdown'
on_ft = ['markdown']
hook_add = '''
  let g:markdown_enable_spell_checking = 0
'''

[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
on_ft = ['java']
if = ''' 0 '''
hook_add = '''
  let g:JaveComplete_AutoStartServer = 0
  " autocmd FileType java setlocal omnifunc=javacomplete#Complete
'''
hook_post_source = '''
  " let g:neomake_java_javac_classpath = g:JavaComplete_LibsPath
  " let g:neomake_java_javac_enabled_makers = ['javac']
  " let g:neomake_java_javac_classpath = g:JavaComplete_SourcesPath
  " let g:neomake_java_javac_options = [
  "   \ '-Xlint',
  "   \ '-sourcepath',
  "   \ getcwd() . '/app/src/main/java' . g:JavaComplete_SourcesPath,
  "   \]
'''

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'vue']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'vue']

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['pug', 'vue']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = '''
  let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'briancollins/vim-jst'
on_ft = ['ejs', 'jst']
hook_add = '''
  " autocmd BufNewFile,BufRead *.ejs set filetype=ejs
  " autocmd BufNewFile,BufRead *._ejs set filetype=ejs
  "
  " function! s:DetectEjs()
  "     if getline(1) =~ '^#!.*\<ejs\>'
  "         set filetype=ejs
  "     endif
  " endfunction
  "
  " autocmd BufNewFile,BufRead * call s:DetectEjs()
'''

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'jwalton512/vim-blade'
on_ft = ['php']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'keith/tmux.vim'
on_ft = ['tmux']

[[plugins]]
repo = 'tkztmk/vim-vala'
on_ft = ['vala']

[[plugins]]
repo = 'vim-scripts/nginx.vim'
on_ft = ['nginx']

[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']

[[plugins]]
repo = 'def-lkb/ocp-indent-vim'
on_ft = ['ocaml']
