[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'gabrielelana/vim-markdown'
on_ft = ['markdown']
if = '0'
hook_add = '''
  let g:markdown_enable_spell_checking = 0
'''

[[plugins]]
repo = 'akhaku/vim-java-unused-imports'
on_ft = ['java']
hook_add = '''
  autocmd! EN BufWritePost *.java UnusedImports
  autocmd! EN BufEnter *.java UnusedImports
'''

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'vue']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'vue']

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['pug', 'vue']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = '''
  let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'briancollins/vim-jst'
on_ft = ['ejs', 'jst']
hook_add = '''
  " autocmd BufNewFile,BufRead *.ejs set filetype=ejs
  " autocmd BufNewFile,BufRead *._ejs set filetype=ejs
  "
  " function! s:DetectEjs()
  "     if getline(1) =~ '^#!.*\<ejs\>'
  "         set filetype=ejs
  "     endif
  " endfunction
  "
  " autocmd BufNewFile,BufRead * call s:DetectEjs()
'''

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'jwalton512/vim-blade'
on_ft = ['php']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'keith/tmux.vim'
on_ft = ['tmux']

[[plugins]]
repo = 'tkztmk/vim-vala'
on_ft = ['vala']

[[plugins]]
repo = 'vim-scripts/nginx.vim'
on_ft = ['nginx']

[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']

[[plugins]]
repo = 'def-lkb/ocp-indent-vim'
on_ft = ['ocaml']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
hook_add = '''
  let g:rustfmt_autosave = 1
  let g:rustfmt_command = $HOME . '/.cargo/bin/rustfmt'
'''

[[plugins]]
repo = 'rhysd/rust-doc.vim'
on_ft = 'rust'
hook_source = '''
  let g:rust_doc#downloaded_rust_doc_dir = $HOME . '/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/share/doc/rust'
"
'''
