#!/bin/bash

if [ ${EUID:-${UID}} = 0 ]; then
  read -p "You are now a ROOT USER. OK to install? (y/N): " yn
  case "$yn" in [yY]*) ;; *) echo "abort." ; exit ;; esac
fi

if ! command -v git &> /dev/null
then
  echo 'Please install git'
  exit 1
fi

CYAN='\033[0;34m'
NC='\033[0m'

gui=false
node=false
zinit=false
vimplug=false

for i in "$@" ; do
  case "$i" in
    'gui'     ) gui=true ;;
    'node'    ) node=true ;;
    'zinit'   ) zinit=true ;;
    'vimplug' ) vimplug=true ;;
  esac
done

mkdir -p ~/.cache/vim
mkdir -p ~/.config/fontconfig
mkdir -p ~/.config/systemd/user
mkdir -p ~/.local/share/systemd/user/
mkdir -p ~/.config/tym
mkdir -p ~/.config/zellij
mkdir -p ~/.go
mkdir -p ~/.local/share/fonts
mkdir -p ~/src
mkdir -p ~/.ipython/profile_default/startup

touch ~/.gitconfig_local
touch ~/.zshrc.pre

ln -fs ~/dotfiles/gitconfig ~/.gitconfig
ln -fs ~/dotfiles/gitignore_global ~/.gitignore_global
ln -fs ~/dotfiles/zshrc ~/.zshrc
ln -fs ~/dotfiles/zshenv ~/.zshenv
# ln -fs ~/dotfiles/bashrc ~/.bashrc
ln -fs ~/dotfiles/tmux.conf ~/.tmux.conf
ln -fs ~/dotfiles/vimrc ~/.vimrc
ln -fsn ~/dotfiles/vim ~/.vim
ln -fsn ~/dotfiles/vim ~/.config/nvim
ln -fs ~/dotfiles/editorconfig ~/.editorconfig
ln -fs ~/dotfiles/tigrc ~/.tigrc
ln -fs ~/dotfiles/pylintrc ~/.pylintrc
ln -fs ~/dotfiles/condarc ~/.condarc
ln -fs ~/dotfiles/systemd/* ~/.local/share/systemd/user/
ln -fs ~/dotfiles/ipython/startup/* ~/.ipython/profile_default/startup
ln -fs ~/dotfiles/zellij.kdl ~/.config/zellij/config.kdl
ln -fs ~/dotfiles/latexmkrc ~/.latexmkrc

# GUI
if $gui; then
  ln -fs ~/dotfiles/ideavimrc ~/.ideavimrc
  ln -fs ~/dotfiles/fonts.conf ~/.config/fontconfig/fonts.conf
  ln -fsn ~/dotfiles/fonts ~/.local/share/fonts/dotfiles

  mkdir -p ~/.wineprefixes

  ln -fs ~/dotfiles/tym/config.lua ~/.config/tym/config.lua
  ln -fs ~/dotfiles/tym/local.lua ~/.config/tym/local.lua

  mkdir -p ~/.mpv
  ln -fs ~/dotfiles/mpv.conf ~/.mpv/input.conf

  mkdir -p ~/.config/environment.d
  ln -fs ~/dotfiles/env.conf ~/.config/environment.d/dotfiles.conf
fi


if $node; then
  if [ ! -d ~/.nodebrew ]; then
    echo
    echo -e "${CYAN}Installing nodebrew${NC}"
    curl -L git.io/nodebrew | perl - setup
    # node_version=16
    # echo -e "${CYAN}Installing node.js ${node_version}${NC}"
    # ~/.nodebrew/nodebrew install-binary ${node_version}
  else
    echo -e "${CYAN}Updating nodebrew${NC}"
    ~/.nodebrew/nodebrew selfupdate
  fi
fi


if $zinit; then
  mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
  git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git"
fi

if $vimplug; then
  sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
fi


echo -e "${CYAN}Done.${NC}"
