vim.keymap.set({ 'n', 'v' }, '<Space>e', ':<C-u>e!<CR>')

vim.keymap.set({ 'n', 'v' }, 'j', 'gj')
vim.keymap.set({ 'n', 'v' }, 'k', 'gk')
vim.keymap.set({ 'n', 'v' }, 'J', '<C-d>zz')
vim.keymap.set({ 'n', 'v' }, 'K', '<C-u>zz')
vim.keymap.set({ 'n', 'v' }, 'H', 'g^')
vim.keymap.set({ 'n', 'v' }, 'L', 'g$')

vim.keymap.set('n', '<C-a>', 'ggVG')
vim.keymap.set('n', '<C-n>', 'gt')
vim.keymap.set('n', '<C-Tab>', 'gt')
vim.keymap.set('n', '<C-p>', 'gT')
vim.keymap.set('n', '<C-S-Tab>', 'gt')
vim.keymap.set('n', '<C-t>', ':<C-u>tabnew<CR>')
